name: CI/CD Pipeline

on:
  push:
    branches:
      - prod

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Archive deployment package
        run: zip -r deployment_package.zip .

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET }}
          aws-region: eu-west-2

      - name: Upload zip to s3
        run: aws s3 cp deployment_package.zip s3://telebottest123/my_bot.zip

      - name: Update Lambda
        run: aws lambda update-function-code --function-name test_bot --s3-bucket telebottest123 --s3-key my_bot.zip

      - name: Clean Up
        run: rm deployment_package.zip
